quarkus:
  application:
    name: simple-app
  http:
    port: 8080
  log:
    level:
      quarkus: info
  native:
    file-encoding: UTF-8
  banner:
    enabled: false
  kubernetes-client:
    namespace: default
  kubernetes-config:
    enabled: true
    config-maps:
      - simple-app-configmap